import { PrismaClient, ShopCategory } from "@prisma/client";

const prisma = new PrismaClient();

const mockShops = [
  {
    id: "shop-1",
    name: "ProTech Solutions",
    slug: "protech-solutions",
    description: '"OEM parts only. Certified Apple technicians. 12-month warranty included."',
    address: "Banani DOHS, Dhaka",
    city: "Dhaka",
    area: "Banani",
    ratingAvg: 4.9,
    reviewCount: 1216,
    priceLevel: 2,
    hasVoucher: true,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.COURIER_PICKUP, ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "battery replacement", "logic board repair", "laptop", "phone"],
    lat: 23.7938,
    lng: 90.4048,
    isFeatured: true,
  },
  {
    id: "shop-2",
    name: "The Gadget Den",
    slug: "the-gadget-den",
    description: '"Express service available. Right around the corner from Main St. Mall."',
    address: "Gulshan 1, Dhaka",
    city: "Dhaka",
    area: "Gulshan",
    ratingAvg: 4.7,
    reviewCount: 84,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "screen replacement", "keyboard repair", "tablet", "smartwatch"],
    lat: 23.7806,
    lng: 90.4168,
    isFeatured: true,
  },
  {
    id: "shop-3",
    name: "Budget Fixer",
    slug: "budget-fixer",
    description: '"Affordable high-quality generic replacement screens. 30-day warranty."',
    address: "Dhanmondi, Dhaka",
    city: "Dhaka",
    area: "Dhanmondi",
    ratingAvg: 4.2,
    reviewCount: 210,
    priceLevel: 1,
    hasVoucher: true,
    freeDelivery: false,
    hasDeals: true,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "display replacement", "screen repair", "console", "printer"],
    lat: 23.7461,
    lng: 90.3742,
    isFeatured: true,
  },
  {
    id: "shop-4",
    name: "MacMaster Repairs",
    slug: "macmaster-repairs",
    description: '"OEM parts only. Certified Apple replacement tools in stock."',
    address: "Mohakhali, Dhaka",
    city: "Dhaka",
    area: "Mohakhali",
    ratingAvg: 4.9,
    reviewCount: 4,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "certified apple support"],
    lat: 23.7776,
    lng: 90.3995,
  },
  {
    id: "shop-5",
    name: "The iDoc Garage",
    slug: "the-idoc-garage",
    description: '"Silicon Valley fixers. Bravest service, and in local pickup."',
    address: "Uttara Sector 11, Dhaka",
    city: "Dhaka",
    area: "Uttara",
    ratingAvg: 4.7,
    reviewCount: 4,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: true,
    hasDeals: false,
    categories: [ShopCategory.COURIER_PICKUP, ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "battery replacement"],
    lat: 23.8759,
    lng: 90.3888,
  },
  {
    id: "shop-6",
    name: "ByteSize Repairs",
    slug: "bytesize-repairs",
    description: '"Express screen editable replacement, and screen screens."',
    address: "Mirpur DOHS, Dhaka",
    city: "Dhaka",
    area: "Mirpur",
    ratingAvg: 4.9,
    reviewCount: 84,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "screen replacement", "keyboard repair"],
    lat: 23.8373,
    lng: 90.3668,
  },
  {
    id: "shop-7",
    name: "AppleCore Solutions",
    slug: "applecore-solutions",
    description: '"Express service available. Right 10am."',
    address: "Badda, Dhaka",
    city: "Dhaka",
    area: "Badda",
    ratingAvg: 4.7,
    reviewCount: 134,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.COURIER_PICKUP, ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "logic board repair", "water damage"],
    lat: 23.7805,
    lng: 90.4267,
  },
  {
    id: "shop-8",
    name: "Main Street Tech",
    slug: "main-street-tech",
    description: '"Main StreetTech. Right, replacement."',
    address: "Tejgaon, Dhaka",
    city: "Dhaka",
    area: "Tejgaon",
    ratingAvg: 4.9,
    reviewCount: 171,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "trackpad replacement", "battery replacement"],
    lat: 23.7603,
    lng: 90.3905,
  },
  {
    id: "shop-9",
    name: "Precision Fix",
    slug: "precision-fix",
    description: '"Affordable high-quality generic replacement battery. 90-day warranty."',
    address: "Rampura, Dhaka",
    city: "Dhaka",
    area: "Rampura",
    ratingAvg: 4.3,
    reviewCount: 210,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: true,
    hasDeals: false,
    categories: [ShopCategory.COURIER_PICKUP, ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "battery replacement", "pickup service"],
    lat: 23.7612,
    lng: 90.4208,
  },
  {
    id: "shop-10",
    name: "Micro-Maestro",
    slug: "micro-maestro",
    description: '"Generic screen. 30-day warranty."',
    address: "Mohammadpur, Dhaka",
    city: "Dhaka",
    area: "Mohammadpur",
    ratingAvg: 4.2,
    reviewCount: 2116,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "micro soldering", "board repair"],
    lat: 23.7658,
    lng: 90.3584,
  },
  {
    id: "shop-11",
    name: "Westside Computery",
    slug: "westside-computery",
    description: "Strictly CPU Dep't replacement for all your repairs. 30-day warranty.",
    address: "Wari, Dhaka",
    city: "Dhaka",
    area: "Wari",
    ratingAvg: 4.7,
    reviewCount: 25,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR],
    specialties: ["MacBook Air M2 repair", "storage replacement", "keyboard repair"],
    lat: 23.7174,
    lng: 90.4183,
  },
  {
    id: "shop-12",
    name: "The Gear Lab",
    slug: "the-gear-lab",
    description: '"Generic screen option. Warranty."',
    address: "Bashundhara, Dhaka",
    city: "Dhaka",
    area: "Bashundhara",
    ratingAvg: 4.2,
    reviewCount: 25,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: [ShopCategory.IN_SHOP_REPAIR, ShopCategory.SPARE_PARTS],
    specialties: ["MacBook Air M2 repair", "replacement parts", "screen repair"],
    lat: 23.8183,
    lng: 90.4328,
  },
];

async function main() {
  console.log("Seeding mock shops...");
  for (const shop of mockShops) {
    await prisma.shop.upsert({
      where: { id: shop.id },
      update: {
        name: shop.name,
        slug: shop.slug,
        description: shop.description,
        address: shop.address,
        city: shop.city,
        area: shop.area,
        lat: shop.lat,
        lng: shop.lng,
        ratingAvg: shop.ratingAvg,
        reviewCount: shop.reviewCount,
        priceLevel: shop.priceLevel,
        hasVoucher: shop.hasVoucher,
        freeDelivery: shop.freeDelivery,
        hasDeals: shop.hasDeals,
        categories: shop.categories,
        specialties: shop.specialties,
        isFeatured: shop.isFeatured || false,
        isActive: true,
        isPublic: true,
        setupComplete: true,
        baseLaborFee: 500,
        inspectionFee: 200,
        pickupFee: 150,
        expressFee: 300,
      },
      create: {
        id: shop.id,
        name: shop.name,
        slug: shop.slug,
        description: shop.description,
        address: shop.address,
        city: shop.city,
        area: shop.area,
        lat: shop.lat,
        lng: shop.lng,
        ratingAvg: shop.ratingAvg,
        reviewCount: shop.reviewCount,
        priceLevel: shop.priceLevel,
        hasVoucher: shop.hasVoucher,
        freeDelivery: shop.freeDelivery,
        hasDeals: shop.hasDeals,
        categories: shop.categories,
        specialties: shop.specialties,
        isFeatured: shop.isFeatured || false,
        isActive: true,
        isPublic: true,
        setupComplete: true,
        baseLaborFee: 500,
        inspectionFee: 200,
        pickupFee: 150,
        expressFee: 300,
      },
    });
  }
  console.log("Done seeding mock shops.");
}

main().finally(() => prisma.$disconnect());
