import type { ApiShop } from "./api";

export const fallbackShops: ApiShop[] = [
  {
    id: "shop-1",
    name: "ProTech Solutions",
    slug: "protech-solutions",
    description: '"OEM parts only. Certified Apple technicians. 12-month warranty included."',
    address: "Banani DOHS, Dhaka",
    city: "Dhaka",
    area: "Banani",
    ratingAvg: 4.9,
    reviewCount: 1216,
    priceLevel: 2,
    hasVoucher: true,
    freeDelivery: false,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "battery replacement", "logic board repair"],
    distanceKm: 1.2,
    etaMinutes: 140,
    resultTag: "Best Value",
    offerSummary: "৳1,850",
  },
  {
    id: "shop-2",
    name: "The Gadget Den",
    slug: "the-gadget-den",
    description: '"Express service available. Right around the corner from Main St. Mall."',
    address: "Gulshan 1, Dhaka",
    city: "Dhaka",
    area: "Gulshan",
    ratingAvg: 4.7,
    reviewCount: 84,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "screen replacement", "keyboard repair"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: "Lowest Price",
    offerSummary: "৳2,100",
  },
  {
    id: "shop-3",
    name: "Budget Fixer",
    slug: "budget-fixer",
    description: '"Affordable high-quality generic replacement screens. 30-day warranty."',
    address: "Dhanmondi, Dhaka",
    city: "Dhaka",
    area: "Dhanmondi",
    ratingAvg: 4.2,
    reviewCount: 210,
    priceLevel: 1,
    hasVoucher: true,
    freeDelivery: false,
    hasDeals: true,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "display replacement", "screen repair"],
    distanceKm: 4.8,
    etaMinutes: 1440,
    resultTag: null,
    offerSummary: "৳1,450",
  },
  {
    id: "shop-4",
    name: "MacMaster Repairs",
    slug: "macmaster-repairs",
    description: '"OEM parts only. Certified Apple replacement tools in stock."',
    address: "Mohakhali, Dhaka",
    city: "Dhaka",
    area: "Mohakhali",
    ratingAvg: 4.9,
    reviewCount: 4,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "certified apple support"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: "Highest Rating",
    offerSummary: "৳1,550",
  },
  {
    id: "shop-5",
    name: "The iDoc Garage",
    slug: "the-idoc-garage",
    description: '"Silicon Valley fixers. Bravest service, and in local pickup."',
    address: "Uttara Sector 11, Dhaka",
    city: "Dhaka",
    area: "Uttara",
    ratingAvg: 4.7,
    reviewCount: 4,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: true,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "battery replacement"],
    distanceKm: 0.5,
    etaMinutes: 180,
    resultTag: "Fastest Service",
    offerSummary: "৳1,990",
  },
  {
    id: "shop-6",
    name: "ByteSize Repairs",
    slug: "bytesize-repairs",
    description: '"Express screen editable replacement, and screen screens."',
    address: "Mirpur DOHS, Dhaka",
    city: "Dhaka",
    area: "Mirpur",
    ratingAvg: 4.9,
    reviewCount: 84,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "screen replacement", "keyboard repair"],
    distanceKm: 0.5,
    etaMinutes: 1440,
    resultTag: "Generic Screen Option",
    offerSummary: "৳1,700",
  },
  {
    id: "shop-7",
    name: "AppleCore Solutions",
    slug: "applecore-solutions",
    description: '"Express service available. Right 10am."',
    address: "Badda, Dhaka",
    city: "Dhaka",
    area: "Badda",
    ratingAvg: 4.7,
    reviewCount: 134,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "logic board repair", "water damage"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: "৳2,050",
  },
  {
    id: "shop-8",
    name: "Main Street Tech",
    slug: "main-street-tech",
    description: '"Main StreetTech. Right, replacement."',
    address: "Tejgaon, Dhaka",
    city: "Dhaka",
    area: "Tejgaon",
    ratingAvg: 4.9,
    reviewCount: 171,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "trackpad replacement", "battery replacement"],
    distanceKm: 1.5,
    etaMinutes: 120,
    resultTag: null,
    offerSummary: "৳1,700",
  },
  {
    id: "shop-9",
    name: "Precision Fix",
    slug: "precision-fix",
    description: '"Affordable high-quality generic replacement battery. 90-day warranty."',
    address: "Rampura, Dhaka",
    city: "Dhaka",
    area: "Rampura",
    ratingAvg: 4.3,
    reviewCount: 210,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: true,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "battery replacement", "pickup service"],
    distanceKm: 0.8,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: "৳1,600",
  },
  {
    id: "shop-10",
    name: "Micro-Maestro",
    slug: "micro-maestro",
    description: '"Generic screen. 30-day warranty."',
    address: "Mohammadpur, Dhaka",
    city: "Dhaka",
    area: "Mohammadpur",
    ratingAvg: 4.2,
    reviewCount: 2116,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "micro soldering", "board repair"],
    distanceKm: 2.1,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: "৳1,750",
  },
  {
    id: "shop-11",
    name: "Westside Computery",
    slug: "westside-computery",
    description: "Strictly CPU Dep't replacement for all your repairs. 30-day warranty.",
    address: "Wari, Dhaka",
    city: "Dhaka",
    area: "Wari",
    ratingAvg: 4.7,
    reviewCount: 25,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "storage replacement", "keyboard repair"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: "৳1,600",
  },
  {
    id: "shop-12",
    name: "The Gear Lab",
    slug: "the-gear-lab",
    description: '"Generic screen option. Warranty."',
    address: "Bashundhara, Dhaka",
    city: "Dhaka",
    area: "Bashundhara",
    ratingAvg: 4.2,
    reviewCount: 25,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR", "SPARE_PARTS"],
    specialties: ["MacBook Air M2 repair", "replacement parts", "screen repair"],
    distanceKm: 1.3,
    etaMinutes: 120,
    resultTag: null,
    offerSummary: "৳1,350",
  },
];

export const offerCards = [
  {
    title: "Free pickup on your first repair",
    subtitle: "Use code MERAMOTNEW to save the courier fee today.",
    href: "/shops?sort=distance&freeDelivery=true&deals=true&q=pickup",
  },
  {
    title: "Laptop battery week",
    subtitle: "Selected vendors are offering up to 15% off original cells.",
    href: "/shops?q=battery&sort=price&deals=true",
  },
];

export const popularCategories = [
  { label: "Phone", sprite: "📱", trend: "High screen repair demand", href: "/shops?q=phone%20screen" },
  { label: "Laptop", sprite: "💻", trend: "Battery and keyboard issues", href: "/shops?q=laptop%20repair" },
  { label: "Tablet", sprite: "🧾", trend: "Port replacement trending", href: "/shops?q=tablet%20repair" },
  { label: "Smartwatch", sprite: "⌚", trend: "Glass and strap repairs", href: "/shops?q=smartwatch" },
  { label: "Gaming Console", sprite: "🎮", trend: "Fan cleaning rising", href: "/shops?q=console%20repair" },
  { label: "Printer", sprite: "🖨️", trend: "Roller and cartridge requests", href: "/shops?q=printer" },
];

export const recentlyViewed = [
  { label: "MacBook Air M2 battery replacement", href: "/shops?q=MacBook%20Air%20M2%20Repair" },
  { label: "iPhone 13 display set", href: "/shops?q=iPhone%2013%20display" },
  { label: "ThinkPad keyboard repair", href: "/shops?q=ThinkPad%20keyboard%20repair" },
  { label: "Samsung S23 charging port fix", href: "/shops?q=Samsung%20S23%20charging%20port" },
];
