import type { ApiShop } from "./api";

export const fallbackShops: ApiShop[] = [
  {
    id: "shop-1",
    name: "ProTech Solutions",
    slug: "protech-solutions",
    description: '"OEM parts only. Certified Apple technicians. 12-month warranty included."',
    address: "Banani DOHS, Dhaka",
    city: "Dhaka",
    area: "Banani",
    lat: 23.790428,
    lng: 90.398003,
    ratingAvg: 4.9,
    reviewCount: 1216,
    priceLevel: 2,
    hasVoucher: true,
    freeDelivery: false,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "battery replacement", "logic board repair", "laptop", "phone"],
    distanceKm: 1.2,
    etaMinutes: 140,
    resultTag: "Best Value",
    offerSummary: '৳1,850',
    inspectionFee: 1850,
    baseLaborFee: 2050,
  },
  {
    id: "shop-2",
    name: "The Gadget Den",
    slug: "the-gadget-den",
    description: '"Express service available. Right around the corner from Main St. Mall."',
    address: "Gulshan 1, Dhaka",
    city: "Dhaka",
    area: "Gulshan",
    lat: 23.791281,
    lng: 90.407776,
    ratingAvg: 4.7,
    reviewCount: 84,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "screen replacement", "keyboard repair", "tablet", "smartwatch"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: "Lowest Price",
    offerSummary: '৳2,100',
    inspectionFee: 2100,
    baseLaborFee: 2300,
  },
  {
    id: "shop-3",
    name: "Budget Fixer",
    slug: "budget-fixer",
    description: '"Affordable high-quality generic replacement screens. 30-day warranty."',
    address: "Dhanmondi, Dhaka",
    city: "Dhaka",
    area: "Dhanmondi",
    lat: 23.744013,
    lng: 90.379081,
    ratingAvg: 4.2,
    reviewCount: 210,
    priceLevel: 1,
    hasVoucher: true,
    freeDelivery: false,
    hasDeals: true,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "display replacement", "screen repair", "console", "printer"],
    distanceKm: 4.8,
    etaMinutes: 1440,
    resultTag: null,
    offerSummary: '৳1,450',
    inspectionFee: 1450,
    baseLaborFee: 1550,
  },
  {
    id: "shop-4",
    name: "MacMaster Repairs",
    slug: "macmaster-repairs",
    description: '"OEM parts only. Certified Apple replacement tools in stock."',
    address: "Mohakhali, Dhaka",
    city: "Dhaka",
    area: "Mohakhali",
    lat: 23.776075,
    lng: 90.403162,
    ratingAvg: 4.9,
    reviewCount: 4,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "certified apple support"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: "Highest Rating",
    offerSummary: '৳1,550',
    inspectionFee: 1550,
    baseLaborFee: 1550,
  },
  {
    id: "shop-5",
    name: "The iDoc Garage",
    slug: "the-idoc-garage",
    description: '"Silicon Valley fixers. Bravest service, and in local pickup."',
    address: "Uttara Sector 11, Dhaka",
    city: "Dhaka",
    area: "Uttara",
    lat: 23.876491,
    lng: 90.374663,
    ratingAvg: 4.7,
    reviewCount: 4,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: true,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "battery replacement"],
    distanceKm: 0.5,
    etaMinutes: 180,
    resultTag: "Fastest Service",
    offerSummary: '৳1,990',
    inspectionFee: 1990,
    baseLaborFee: 1990,
  },
  {
    id: "shop-6",
    name: "ByteSize Repairs",
    slug: "bytesize-repairs",
    description: '"Express screen editable replacement, and screen screens."',
    address: "Mirpur DOHS, Dhaka",
    city: "Dhaka",
    area: "Mirpur",
    lat: 23.799254,
    lng: 90.373466,
    ratingAvg: 4.9,
    reviewCount: 84,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "screen replacement", "keyboard repair"],
    distanceKm: 0.5,
    etaMinutes: 1440,
    resultTag: "Generic Screen Option",
    offerSummary: '৳1,700',
    inspectionFee: 1700,
    baseLaborFee: 1700,
  },
  {
    id: "shop-7",
    name: "AppleCore Solutions",
    slug: "applecore-solutions",
    description: '"Express service available. Right 10am."',
    address: "Badda, Dhaka",
    city: "Dhaka",
    area: "Badda",
    lat: 23.778462,
    lng: 90.430006,
    ratingAvg: 4.7,
    reviewCount: 134,
    priceLevel: 3,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "logic board repair", "water damage"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: '৳2,050',
    inspectionFee: 2050,
    baseLaborFee: 2150,
  },
  {
    id: "shop-8",
    name: "Main Street Tech",
    slug: "main-street-tech",
    description: '"Main StreetTech. Right, replacement."',
    address: "Tejgaon, Dhaka",
    city: "Dhaka",
    area: "Tejgaon",
    lat: 23.763010,
    lng: 90.397188,
    ratingAvg: 4.9,
    reviewCount: 171,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "trackpad replacement", "battery replacement"],
    distanceKm: 1.5,
    etaMinutes: 120,
    resultTag: null,
    offerSummary: '৳1,700',
    inspectionFee: 1700,
    baseLaborFee: 1900,
  },
  {
    id: "shop-9",
    name: "Precision Fix",
    slug: "precision-fix",
    description: '"Affordable high-quality generic replacement battery. 90-day warranty."',
    address: "Rampura, Dhaka",
    city: "Dhaka",
    area: "Rampura",
    lat: 23.759799,
    lng: 90.416242,
    ratingAvg: 4.3,
    reviewCount: 210,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: true,
    hasDeals: false,
    categories: ["COURIER_PICKUP", "IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "battery replacement", "pickup service"],
    distanceKm: 0.8,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: '৳1,600',
    inspectionFee: 1600,
    baseLaborFee: 1800,
  },
  {
    id: "shop-10",
    name: "Micro-Maestro",
    slug: "micro-maestro",
    description: '"Generic screen. 30-day warranty."',
    address: "Mohammadpur, Dhaka",
    city: "Dhaka",
    area: "Mohammadpur",
    lat: 23.768931,
    lng: 90.359862,
    ratingAvg: 4.2,
    reviewCount: 2116,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "micro soldering", "board repair"],
    distanceKm: 2.1,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: '৳1,750',
    inspectionFee: 1750,
    baseLaborFee: 1750,
  },
  {
    id: "shop-11",
    name: "Westside Computery",
    slug: "westside-computery",
    description: "Strictly CPU Dep't replacement for all your repairs. 30-day warranty.",
    address: "Wari, Dhaka",
    city: "Dhaka",
    area: "Wari",
    lat: 23.721946,
    lng: 90.420248,
    ratingAvg: 4.7,
    reviewCount: 25,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR"],
    specialties: ["MacBook Air M2 repair", "storage replacement", "keyboard repair"],
    distanceKm: 0.5,
    etaMinutes: 60,
    resultTag: null,
    offerSummary: '৳1,600',
    inspectionFee: 1600,
    baseLaborFee: 1600,
  },
  {
    id: "shop-12",
    name: "The Gear Lab",
    slug: "the-gear-lab",
    description: '"Generic screen option. Warranty."',
    address: "Bashundhara, Dhaka",
    city: "Dhaka",
    area: "Bashundhara",
    lat: 23.808686,
    lng: 90.421096,
    ratingAvg: 4.2,
    reviewCount: 25,
    priceLevel: 2,
    hasVoucher: false,
    freeDelivery: false,
    hasDeals: false,
    categories: ["IN_SHOP_REPAIR", "SPARE_PARTS"],
    specialties: ["MacBook Air M2 repair", "replacement parts", "screen repair"],
    distanceKm: 1.3,
    etaMinutes: 120,
    resultTag: null,
    offerSummary: '৳1,350',
    inspectionFee: 1350,
    baseLaborFee: 1550,
  },
];

export const offerCards = [
  {
    title: "Free pickup on your first repair",
    subtitle: "Use code MERAMOTNEW to save the courier fee today.",
    href: "/shops?sort=distance&freeDelivery=true&deals=true&q=pickup",
  },
  {
    title: "Laptop battery week",
    subtitle: "Selected vendors are offering up to 15% off original cells.",
    href: "/shops?q=battery&sort=price&deals=true",
  },
];

export const popularCategories = [
  { label: "Phone", sprite: "📱", trend: "High screen repair demand", href: "/shops?q=phone" },
  { label: "Laptop", sprite: "💻", trend: "Battery and keyboard issues", href: "/shops?q=laptop" },
  { label: "Tablet", sprite: "🧾", trend: "Port replacement trending", href: "/shops?q=tablet" },
  { label: "Smartwatch", sprite: "⌚", trend: "Glass and strap repairs", href: "/shops?q=smartwatch" },
  { label: "Gaming Console", sprite: "🎮", trend: "Fan cleaning rising", href: "/shops?q=console" },
  { label: "Printer", sprite: "🖨️", trend: "Roller and cartridge requests", href: "/shops?q=printer" },
];

export const recentlyViewed = [
  { label: "MacBook Air M2 battery replacement", href: "/shops?q=MacBook%20Air%20M2%20Repair" },
  { label: "iPhone 13 display set", href: "/shops?q=iPhone%2013%20display" },
  { label: "ThinkPad keyboard repair", href: "/shops?q=ThinkPad%20keyboard%20repair" },
  { label: "Samsung S23 charging port fix", href: "/shops?q=Samsung%20S23%20charging%20port" },
];
